{% set name = "tb3py" %}
{% set version = "2021.7.11" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tb3py-{{ version }}.tar.gz
  sha256: 6105173883cd6cbf8544413aedf5e5aa4f47bcaa62be9a8ec8c94a951345f9cd

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - requests >=2.26.0
  run:
    - jarvis-tools
    - julia >=0.5.6
    - numpy >=1.19.5
    - pytest
    - python >={{ python_min }}
    - requests >=2.26.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - tb3py
    - tb3py.tests


about:
  home: https://github.com/usnistgov/tb3py
  summary: 'tb3: an open-source software package for accurate and efficient electronic structure calculations using tight-binding (TB), including three-body interactions. https://pages.nist.gov/ThreeBodyTB.jl'
  license: NIST-PD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - knc6
